// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ekixzytbmgrjqcnriqnq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVraXh6eXRibWdyanFjbnJpcW5xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI2NzAyMDMsImV4cCI6MjA3ODI0NjIwM30.nF9GhR8H697iCs4gEyXD7eIgQHSO36vEAnKF2518hi4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});